name: Build

on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://copsteam.pactflow.io
  PACT_PROVIDER: pactflow-example-provider
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
  REACT_APP_API_BASE_URL: http://localhost:3001
  GIT_COMMIT: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install
        run: npm i
      - name: Test
        env:
          PACT_PROVIDER: ${{ env.PACT_PROVIDER }}
        run: make test
      - name: Publish pacts between pactflow-example-consumer and ${{ env.PACT_PROVIDER }}
        run: GIT_BRANCH=${GIT_REF:11} make publish_pacts
        env:
          PACT_PROVIDER: ${{ env.PACT_PROVIDER }}

  # Runs on branches as well, so we know the status of our PRs
  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Can I deploy?
        run: GIT_BRANCH=${GIT_REF:11} make can_i_deploy

  # Only deploy from master
  deploy:
    runs-on: ubuntu-latest
    needs: can-i-deploy
    steps:
      - uses: actions/checkout@v3
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Deploy
        run: GIT_BRANCH=${GIT_REF:11} make deploy
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/test'